Internal Server Error: /App1/areas/
Traceback (most recent call last):
  File "/home/obe/prueba/venv3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/obe/prueba/venv3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/obe/prueba/App1/views.py", line 30, in areas_practica
    return render(request, 'areas_practica.html')
  File "/home/obe/prueba/venv3.10/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/obe/prueba/venv3.10/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/obe/prueba/venv3.10/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: areas_practica.html
Internal Server Error: /App1/areas/
Traceback (most recent call last):
  File "/home/obe/prueba/venv3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/obe/prueba/venv3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/obe/prueba/App1/views.py", line 30, in areas_practica
    return render(request, 'areas_practica.html')
  File "/home/obe/prueba/venv3.10/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/obe/prueba/venv3.10/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/obe/prueba/venv3.10/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: areas_practica.html
